### ISSUE TITLE
Delete Series

### ISSUE THREAD

**Issue by platinummonkey** [tempodb/tempodb-python#25]
The ability to delete series would be useful. Currently only deleting data from a series is possible.

**Comment by blakesmith** [comment]
Hi Cody,

Thanks for filing the issue, we're actively working on delete series right now. Expect to hear from us soon about its release.

Blake

**Comment by blakesmith** [comment]
Added in: 3502502d0b1f8372951265560adecd0d517899a1, which is available in version 0.5.0 of the client on pypi.

Thanks for the feedback!
