### ISSUE TITLE
create_database does not work

### ISSUE THREAD

**Issue by moodh** [tempodb/tempodb-python#30]
Hey, noticed an error in client.py, Database is not imported so the following call doesn't work (unless it shouldn't work in which case just close this issue :))

> > > import tempodb
> > > t = tempodb.Client('key', 'secret')
> > > t.create_database('test')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "foobar/tempodb/client.py", line 49, in create_database
> > >     database = Database(key, secret)
> > > NameError: global name 'Database' is not defined

**Comment by myagley** [comment]
Yes, this is an undocumented api that was meant to be removed. The only way to create a new database is through the website at http://tempo-db.com.

Thanks for pointing it out!
